docs/assets/css/main.css, docs/explorer.html, jekyll/assets/css/main.css, jekyll/explorer.md
=> Publish risk data indicators

docs/explorer.html, docs/index.html, jekyll/explorer.md, jekyll/index.md
Few updates to dev center explorer page:
1. Updating guide to Quick start guide
2. Updating starter text
3. fixing links
4. updating tables
=> Updating Guide 

docs/explorer.html, jekyll/explorer.md
with max values for each hazard
=> Updating forward looking risk exposure table 

clients/python/sust/api/climate_explorer.py
Added the portfolio create and asset import endpoints.
=> Add Portfolio Create and Asset Import endpoints

docs/explorer.html, jekyll/Gemfile.lock, jekyll/explorer.md
Adding a brief description on projects and permissions.
=> Introductory description on projects

clients/python/sust/api/climate_explorer.py
This avoids having to pull the entire AssetList from
the API in the event that the caller simply wants
to get physical risk timeseries or summary data for
all of the assets, which is quite common.
=> Move physical_risk calls to Portfolio

docs/explorer.html, docs/userguide.html, jekyll/explorer.md, jekyll/userguide.md
*Updated “Wildfire Risk” “Heat map coding range” 
*Updated “Tropical Cyclones” “Heat map coding range” 
*Updated “Inland Flooding” “Heat map coding range”
*Updated “Drought (SPEI)” “Heat map coding range”
=> Updated Forward Looking Reporting Outcomes in QuickStart Guide with New Values 

docs/userguide.html, jekyll/userguide.md
*Updated image files to correct case structure
=> Fixed image file naming

docs/explorer.html, jekyll/explorer.md
*Updated Quickstart Guide to include product video
=> Added Product Video

docs/explorer.html, jekyll/explorer.md
*Centered video on Quickstart page
=> Updated Product Video

docs/explorer.html, docs/userguide.html, jekyll/explorer.md, jekyll/userguide.md
*Added new labels and text for Wildfire in User Guide
*Added indicator of Water stress to Quickstart & User Guide
=> Updated Hazards (Wildfire & Water Stress)

docs/explorer.html, docs/userguide.html, jekyll/explorer.md, jekyll/userguide.md
*Updated last table in Quickstart for wildfire
*Updated wildfire user guide
=> Updated Wildfire in User Guide & Quickstart

docs/FAQs.html, docs/index.html, jekyll/FAQs.md, jekyll/index.md
*Added question for fire under FAQ
*Added question for flooding/cyclones under FAQ
=> Added FAQs for fire and flooding

docs/explorer.html, jekyll/explorer.md
=> Updated cyclone obs_freq in quicksatart

docs/updates.html, jekyll/updates.md
*Updated product update text for first update
=> Updated Product Updates

docs/dataguide.html, jekyll/Gemfile.lock, jekyll/dataguide.md
Found a typo in a customer call earlier
=> fix header

jupyter-notebooks/ClimateDataStudio/requirements.txt
Updating API Key as an environmental variable.  
Former API Key has been rotated.
=> CDS Updates

clients/python/sphinx/src/index.rst, docs/py/index.html
=> Pushing html update

jekyll/dataguide-staging.md
Standing up the staged version of the data guide for cross team review
=> Staging data guide changes

docs/api.html, jekyll/api.md
@jpcedenog I added a few small changes for clarity to the `api guide`.  I also updated the existing Jupyter notebook to use the new headers.
=> Updates to example Jupyter Notebook for using headers.  Small api guide updates for clarity.

cloudbuild.yaml, jekyll/dataguide.md, jekyll/dataguide_hazards/cyclones.md, jekyll/explorer.md
Update cyclone resolution from 50km to 10km, food resolution from 4km to 1km
=> Tb resolutionupdate

jekyll/dataguide_hazards/waterstress.md
Redo of Matt's PR from several months ago that went stale when the file moved. 
Related to [CS-110](https://sust.atlassian.net/jira/software/projects/CS/boards/1?selectedIssue=CS-110).
Text added: "The indicator captures both meteorological factors as well as anthropogenic factors associated with water stress."
=> Update unified water stress description

docs/csvdatasetguide.html, jekyll/csvdatasetguide.md
Clean up out-of-date descriptions of monthly and yearly cadences for fire and flood, as well as some other issues
=> update monthly files to yearly

docs/FAQs.html, docs/var.html, jekyll/FAQs.md, jekyll/dataguide_hazards/var.md
Updates for [CS-191](https://sust.atlassian.net/jira/software/projects/CS/boards/1?selectedIssue=CS-191)
This includes:
1. A table giving a better overview of asset types for Var
2. New Q in FAQ on flooding doorstep values
3. New Q in FAQ on L/M/H thresholding
=> Data Guide Updates

jekyll/dataguide.md, jekyll/dataguide_hazards/cyclones.md, jekyll/dataguide_hazards/heatwaves.md, jekyll/dataguide_hazards/sea_level_rise.md, jekyll/dataguide_hazards/waterstress.md
Minor updates to the markdown files, adding descriptions for the newly added Obs Sea level rise and Obs Heatwaves indicators. Minor typo/clarity edits otherwise.
=> Tb jul2023

docs/csvdatasetguide.html, docs/cyclones.html, docs/dashboardguide.html, docs/dataguide.html, docs/heatwaves.html, docs/sea_level_rise.html, docs/updates.html, docs/waterstress.html, jekyll/csvdatasetguide.md, jekyll/dashboardguide.md, jekyll/updates.md
* Build the html pages from Tristans previous PRs
* Add BI documentation to some areas
* Add release notes
=> New Release Updates

jekyll/_docs/nature-api-guide.md, jekyll/_docs/nature-data-guide.md
Adding a description doc for the indicators for durability
Updated intro line for nature API doc
=> Sumamry data descriptions for durability indicators

jupyter-notebooks/Dockerfile, jupyter-notebooks/requirements.txt
Updated Docker container with new dependencies
=> Added new jyupter notebook for REIT workflow

docs/api-guide.html, docs/coming-soon.html, docs/cyclones.html, docs/dashboard-guide.html, docs/data-guide.html, docs/dataset-guide.html, docs/faq.html, docs/flood.html, docs/heatwaves.html, docs/nature-api-guide.html, docs/nature-data-guide.html, docs/notebooks.html, docs/sea-level-rise.html, docs/search.html, docs/search.json, docs/snowflake.html, docs/updates.html, docs/user-guide.html, docs/value-at-risk.html, docs/water-stress.html, docs/wildfire.html, docs/zonal-climate-stats.html, jekyll/_docs/data-guide.md, jekyll/_docs/sea-level-rise.md, jekyll/_docs/value-at-risk.md
Updates to 3 dev center `.md` files on this branch:
(1) fix typo in `data-guide.md` 
(2) add 24 month smoother in `sea-level-rise.md`
(3) overhaul of language in the `value-at-risk.md`
=> Ms value at risk

jekyll/hack/README.md
Update documentation for local build and run
=> Fix readme
